version: "3"

services:
  polls:
    build: .
    env_file:
      - .env
    environment:
      - DB_URL=postgres://postgres:postgres@db:5432/postgres
      - DEBUG=False
    depends_on:
      - db
    ports:
      - 8000:8000
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres